# Generated by Django 3.1.1 on 2020-11-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'versions',
            },
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_id', models.IntegerField()),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=20)),
                ('t_time', models.CharField(max_length=50)),
                ('max_num', models.IntegerField()),
                ('ssd', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('t_code', models.CharField(max_length=100)),
                ('v_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areaInfo.versions', verbose_name='更新版本号')),
            ],
            options={
                'db_table': 'area_info',
            },
        ),
    ]
