# Generated by Django 3.1.1 on 2020-11-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areaInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areainfo',
            name='get_id',
        ),
    ]
